a <- read.table("controlpoints",header=T,sep="|")
library(interp)
lon.i <- interp(a$imgx, a$imgy, a$lon, nx=500,ny=500)
image(lon.i)
lat.i <- interp(a$imgx, a$imgy, a$lat, nx=500,ny=500)
image(lat.i)
lon.t <- as.table(lon.i$z)
colnames(lon.t) <- seq(0,499)
rownames(lon.t) <- seq(0,499)
lat.t <- as.table(lat.i$z)
out <- data.frame(as.data.frame(lon.t),as.data.frame(lat.t)$Freq)
# colnames(out) <- c("x","y","lon","lat")
write.table(out, file="predict", quote = F, sep=",", na = "", col.names = F, row.names=F)
